let data = {
	"$myro": "",
	"$wen": "",
	"00": "00 Token",
	"0x0": "",
	"1000sats": "",
	"10set": "Tenset",
	"1inch": "1inch",
	"aave": "Aave",
	"abt": "Arcblock",
	"ach": "Alchemy Pay",
	"acs": "ACryptoS",
	"ada": "Cardano",
	"aed": "Emirati Dirham",
	"aergo": "Aergo",
	"aero": "Aero Coin",
	"aevo": "",
	"afn": "Afghan Afghani",
	"agi": "SingularityNET",
	"agix": "SingularityNET",
	"agld": "Adventure Gold",
	"ai": "Flourishing AI",
	"aioz": "Aioz Network",
	"akt": "Akash Network",
	"alcx": "Alchemix",
	"aleph": "Aleph.im",
	"alex": "Alexandrite",
	"algo": "Algorand",
	"alice": "My Neighbor Alice",
	"all": "Albanian Lek",
	"alph": "Alephium",
	"alt": "ALTcoin",
	"alusd": "Alchemix USD",
	"amd": "Armenian Dram",
	"amp": "Amp",
	"ampl": "Ampleforth",
	"andy": "",
	"ang": "Dutch Guilder",
	"ankr": "Ankr Network",
	"ant": "Aragon",
	"aoa": "Angolan Kwanza",
	"ape": "ApeCoin",
	"apex": "ApexCoin",
	"api3": "API3",
	"apl": "Apollo Currency",
	"apt": "Aptos",
	"apu": "",
	"ar": "Arweave",
	"arb": "Arbitrum",
	"ark": "ARK",
	"arkm": "",
	"arpa": "ARPA Chain",
	"ars": "Argentine Peso",
	"asm": "Assemble Protocol",
	"ast": "AirSwap",
	"astr": "Astar",
	"ata": "Automata Network",
	"ath": "Atheios",
	"atom": "Cosmos",
	"ats": "Austrian Schilling",
	"auction": "Bounce Token AUCTION",
	"aud": "Australian Dollar",
	"audio": "Audius",
	"aurora": "Aurora",
	"avax": "Avalanche",
	"avt": "Aventus",
	"awg": "Aruban or Dutch Guilder",
	"axl": "Axelar",
	"axs": "Axie Infinity",
	"azero": "Aleph Zero",
	"azm": "Azerbaijani Manat",
	"azn": "Azerbaijan Manat",
	"babydoge": "BabyDoge ETH",
	"badger": "Badger DAO",
	"bake": "BakeryToken",
	"bal": "Balancer",
	"bam": "Bosnian Convertible Mark",
	"band": "Band Protocol",
	"bat": "Basic Attention Token",
	"bb": "",
	"bbd": "Barbadian or Bajan Dollar",
	"bch": "Bitcoin Cash",
	"bdt": "Bangladeshi Taka",
	"bdx": "Beldex",
	"beam": "Beam",
	"beer": "BEER Coin",
	"bef": "Belgian Franc",
	"bgb": "Bitget Token",
	"bgn": "Bulgarian Lev",
	"bhd": "Bahraini Dinar",
	"bico": "Biconomy",
	"bif": "Burundian Franc",
	"bigtime": "",
	"bit": "BitDAO",
	"blast": "BLAST",
	"bld": "",
	"blur": "Blur",
	"blz": "Bluzelle",
	"bmd": "Bermudian Dollar",
	"bnb": "Binance Coin",
	"bnd": "Bruneian Dollar",
	"bnt": "Bancor Network",
	"bob": "Bolivian Bolíviano",
	"boba": "Boba Network",
	"boden": "",
	"bome": "",
	"bond": "BarnBridge",
	"bone": "Bone ShibaSwap",
	"bonk": "",
	"bora": "BORA",
	"borg": "",
	"bpx": "Black Phoenix",
	"brett": "",
	"brl": "Brazilian Real",
	"bsd": "Bahamian Dollar",
	"bsv": "Bitcoin SV",
	"bsw": "Biswap",
	"btc": "Bitcoin",
	"btc.b": "",
	"btcb": "Bitcoin BEP2",
	"btg": "Bitcoin Gold",
	"btn": "Bhutanese Ngultrum",
	"btrst": "Braintrust",
	"btt": "BitTorrent",
	"busd": "Binance USD",
	"bwp": "Botswana Pula",
	"byn": "Belarusian Ruble",
	"byr": "Belarusian Ruble",
	"bzd": "Belizean Dollar",
	"c98": "Coin98",
	"cad": "Canadian Dollar",
	"caf": "",
	"cake": "PancakeSwap",
	"canto": "",
	"cbeth": "Coinbase Wrapped Staked ETH",
	"cdai": "Compound Dai",
	"cdf": "Congolese Franc",
	"cdt": "Blox",
	"cel": "Celsius Network",
	"celo": "Celo",
	"celr": "Celer Network",
	"ceth": "",
	"cfg": "Centrifuge",
	"cfx": "Conflux",
	"cgld": "Celo Gold",
	"cheel": "",
	"chex": "",
	"chf": "Swiss Franc",
	"chr": "Chromia",
	"chz": "Chiliz",
	"ckb": "Nervos Network",
	"clp": "Chilean Peso",
	"clv": "Clover Finance",
	"cnh": "Chinese Yuan Renminbi Offshore",
	"cny": "Chinese Yuan Renminbi",
	"comai": "",
	"comp": "Compound",
	"cop": "Colombian Peso",
	"coq": "",
	"core": "Core Group Asset",
	"corechain": "",
	"corgiai": "",
	"coti": "COTI",
	"coval": "COVAL",
	"cqt": "Covalent",
	"crc": "Costa Rican Colon",
	"cro": "Crypto.com Chain",
	"crpt": "Crypterium",
	"crv": "Curve DAO Token",
	"cspr": "Casper",
	"ctc": "CarterCoin",
	"ctsi": "Cartesi",
	"ctx": "Cryptex Finance",
	"cuc": "Cuban Convertible Peso",
	"cup": "Cuban Peso",
	"cvc": "Civic",
	"cve": "Cape Verdean Escudo",
	"cvx": "Convex Finance",
	"cwbtc": "",
	"cyp": "Cypriot Pound",
	"czk": "Czech Koruna",
	"dag": "Constellation",
	"dai": "DAI",
	"dao": "DAO Maker",
	"dar": "Mines of Dalarnia",
	"dash": "Digital Cash",
	"dcr": "Decred",
	"ddx": "DerivaDAO",
	"degen": "",
	"dem": "German Deutsche Mark",
	"deso": "Decentralized Social",
	"dexe": "DeXe",
	"dext": "DEXTools",
	"dfi": "DfiStarter",
	"dgb": "DigiByte",
	"dia": "Dia",
	"dimo": "DIMO",
	"djf": "Djiboutian Franc",
	"dkk": "Danish Krone",
	"dnt": "District0x",
	"dog": "DogeSwap",
	"doge": "Dogecoin",
	"dop": "Dominican Peso",
	"dora": "Dora Factory",
	"dot": "Polkadot",
	"drep": "Drep [new]",
	"dydx": "dYdX",
	"dym": "",
	"dyp": "DeFi Yield Protocol",
	"dzd": "Algerian Dinar",
	"ecoin": "E-coin Finance",
	"edu": "EduCoin",
	"edum": "",
	"eek": "Estonian Kroon",
	"eeth": "",
	"egld": "Elrond",
	"egp": "Egyptian Pound",
	"ela": "Elastos",
	"elf": "aelf",
	"elg": "EscoinToken",
	"eml": "",
	"ena": "",
	"enj": "Enjin Coin",
	"ens": "Ethereum Name Service",
	"eos": "EOS",
	"ern": "Eritrean Nakfa",
	"esp": "Spanish Peseta",
	"etb": "Ethiopian Birr",
	"etc": "Ethereum Classic",
	"eth": "Ethereum",
	"eth2": "Ethereum 2.0",
	"ethdydx": "",
	"ethfi": "",
	"ethw": "",
	"ethx": "",
	"eur": "Euro",
	"eurc": "",
	"euroc": "Euro Coin",
	"ever": "EverLife.AI",
	"ezeth": "",
	"farm": "Harvest Finance",
	"fdusd": "",
	"fei": "Fei USD",
	"fet": "Fetch.ai",
	"fida": "Bonfida",
	"fil": "Filecoin",
	"fim": "Finnish Markka",
	"fis": "Stafi",
	"fjd": "Fijian Dollar",
	"fkp": "Falkland Island Pound",
	"floki": "Baby Moon Floki",
	"flow": "Flow",
	"flr": "FLARE",
	"flux": "Datamine FLUX",
	"fnsa": "",
	"fort": "Forta",
	"forth": "Ampleforth Governance Token",
	"fox": "Shapeshift FOX Token",
	"frax": "Frax",
	"frf": "French Franc",
	"friend": "",
	"frxeth": "",
	"ftm": "Fantom",
	"ftn": "",
	"ftt": "FarmaTrust",
	"fx": "Function X",
	"fxs": "Frax Share",
	"gaj": "Gaj Finance",
	"gal": "Project Galaxy",
	"gala": "Gala",
	"gas": "Gas",
	"gbp": "British Pound",
	"gel": "Georgian Lari",
	"gf": "GuildFi",
	"gfi": "Goldfinch",
	"ggp": "Guernsey Pound",
	"ghc": "Ghanaian Cedi",
	"ghs": "Ghanaian Cedi",
	"ghst": "Aavegotchi",
	"gip": "Gibraltar Pound",
	"glm": "Golem",
	"glmr": "Moonbeam",
	"gmd": "Gambian Dalasi",
	"gmt": "Stepn",
	"gmx": "Goldmaxcoin",
	"gnf": "Guinean Franc",
	"gno": "Gnosis",
	"gns": "Gains Network",
	"gnt": "GreenTrust",
	"gods": "Gods Unchained",
	"grd": "Greek Drachma",
	"grin": "Grin",
	"grt": "The Graph",
	"gst": "Green Satoshi Token",
	"gt": "GateToken",
	"gtc": "Gitcoin",
	"gtq": "Guatemalan Quetzal",
	"gusd": "Gemini US Dollar",
	"gxc": "Gx Coin",
	"gyd": "Guyanese Dollar",
	"gyen": "GYEN",
	"h2o": "Hydrominer",
	"hbar": "Hedera",
	"hbtc": "Huobi BTC",
	"hft": "Hashflow",
	"high": "Highstreet",
	"hkd": "Hong Kong Dollar",
	"hnl": "Honduran Lempira",
	"hnt": "Helium",
	"honey": "Honey",
	"hopr": "HOPR",
	"hot": "Hydro Protocol",
	"hrk": "Croatian Kuna",
	"ht": "Huobi Token",
	"htg": "Haitian Gourde",
	"huf": "Hungarian Forint",
	"icp": "Internet Computer",
	"icx": "ICON Project",
	"id": "TrigID",
	"idex": "IDEX",
	"idr": "Indonesian Rupiah",
	"iep": "Irish Pound",
	"ils": "Israeli Shekel",
	"ilv": "Illuvium",
	"imp": "Isle of Man Pound",
	"imx": "Immutable X",
	"index": "Index Cooperative",
	"inj": "Injective",
	"inr": "Indian Rupee",
	"inv": "Inverse Finance",
	"io": "",
	"iost": "IOS token",
	"iota": "",
	"iotx": "IoTeX",
	"iq": "Everipedia",
	"iqd": "Iraqi Dinar",
	"irr": "Iranian Rial",
	"isk": "Icelandic Krona",
	"itl": "Italian Lira",
	"jasmy": "Jasmy",
	"jep": "Jersey Pound",
	"jmd": "Jamaican Dollar",
	"jod": "Jordanian Dinar",
	"joe": "JOE",
	"jpy": "Japanese Yen",
	"jst": "JUST",
	"jto": "",
	"jup": "Jupiter",
	"karrat": "",
	"kas": "",
	"kava": "Kava",
	"kcs": "Kucoin",
	"kda": "Kadena",
	"keep": "Keep Network",
	"kes": "Kenyan Shilling",
	"kgs": "Kyrgyzstani Som",
	"khr": "Cambodian Riel",
	"klay": "Klaytn",
	"kmf": "Comorian Franc",
	"kmno": "",
	"knc": "Kyber Network Crystals",
	"kpw": "North Korean Won",
	"krl": "Kryll",
	"krw": "South Korean Won",
	"ksm": "Kusama",
	"kub": "Bitkub Coin",
	"kuji": "Kujira",
	"kwd": "Kuwaiti Dinar",
	"kyd": "Caymanian Dollar",
	"kzt": "Kazakhstani Tenge",
	"ladys": "",
	"lak": "Lao Kip",
	"lbp": "Lebanese Pound",
	"lcx": "LCX",
	"ldo": "Lido DAO Token",
	"leo": "LEOcoin",
	"lft": "",
	"link": "Chainlink",
	"lit": "Litentry",
	"lkr": "Sri Lankan Rupee",
	"loka": "League of Kingdoms Arena",
	"loom": "Loom Network",
	"lpt": "Livepeer (LPT)",
	"lqty": "Liquity",
	"lrc": "Loopring",
	"lrd": "Liberian Dollar",
	"lsd": "LightSpeedCoin",
	"lseth": "Liquid Staked Ethereum",
	"lsk": "Lisk",
	"lsl": "Basotho Loti",
	"ltc": "Litecoin",
	"ltl": "Lithuanian Litas",
	"luf": "Luxembourg Franc",
	"luna": "Terra",
	"lunc": "",
	"lusd": "Limited USD",
	"lvl": "Latvian Lat",
	"lyd": "Libyan Dinar",
	"lyx": "",
	"lyxe": "LUKSO",
	"mad": "Moroccan Dirham",
	"maga": "",
	"magic": "MAGIC",
	"mana": "Mana Coin Decentraland",
	"manta": "",
	"mask": "Mask Network",
	"math": "MATH",
	"matic": "Polygon",
	"mav": "",
	"mavia": "",
	"mbx": "MobieCoin",
	"mco2": "Moss Carbon Credit",
	"mcoin": "",
	"mdl": "Moldovan Leu",
	"mdt": "Measurable Data Token",
	"media": "Media Network",
	"meme": "Pepe",
	"meth": "Mirrored Ether",
	"metis": "MetisDAO",
	"mew": "",
	"mga": "Malagasy Ariary",
	"mgf": "Malagasy Franc",
	"mina": "Mina",
	"mir": "Mirror Protocol",
	"mkd": "Macedonian Denar",
	"mkr": "Maker",
	"mkusd": "",
	"mln": "Enzyme",
	"mmk": "Burmese Kyat",
	"mmx": "",
	"mnde": "Marinade",
	"mnt": "Mongolian Tughrik",
	"mobile": "",
	"mog": "",
	"mona": "Monavale",
	"mop": "Macau Pataca",
	"movr": "Moonriver",
	"mpl": "Maple",
	"mplx": "",
	"mro": "Mauritanian Ouguiya",
	"mrs": "MarsCoin",
	"mru": "Mauritanian Ouguiya",
	"msol": "Marinade Staked SOL",
	"mtl": "Maltese Lira",
	"mubi": "",
	"multi": "Multichain",
	"mur": "Mauritian Rupee",
	"muse": "Muse",
	"mvr": "Maldivian Rufiyaa",
	"mwk": "Malawian Kwacha",
	"mx": "MarsX",
	"mxc": "MXC",
	"mxn": "Mexican Peso",
	"mxv": "",
	"myr": "Malaysian Ringgit",
	"myth": "",
	"mzm": "Mozambican Metical",
	"mzn": "Mozambican Metical",
	"nad": "Namibian Dollar",
	"nct": "Polyswarm",
	"near": "NEAR Protocol",
	"neo": "NEO",
	"neon": "",
	"nest": "NEST Protocol",
	"nexo": "NEXO",
	"nft": "NFT",
	"ngn": "Nigerian Naira",
	"nio": "Nicaraguan Cordoba",
	"nkn": "NKN",
	"nlg": "Dutch Guilder",
	"nmr": "Numeraire Network",
	"nmt": "NFTMart Token",
	"nok": "Norwegian Krone",
	"nos": "nOS",
	"not": "",
	"npc": "NPCcoin",
	"npr": "Nepalese Rupee",
	"npxs": "Pundi X",
	"ntrn": "Neutron",
	"nu": "NuCypher",
	"nxm": "NXM",
	"nzd": "New Zealand Dollar",
	"oas": "",
	"ocean": "Ocean Protocol",
	"ogn": "Origin Token",
	"ohm": "Olympus v1",
	"okb": "Okex",
	"okt": "OEC Token",
	"olas": "",
	"om": "MANTRA DAO",
	"omg": "Omisego",
	"omi": "ECOMI",
	"omikami": "",
	"omni": "Omni",
	"omr": "Omani Rial",
	"ondo": "",
	"one": "Menlo One",
	"ong": "SoMee.Social",
	"ont": "Ontology",
	"ooki": "Ooki Protocol",
	"op": "Optimism",
	"orai": "Oraichain Token",
	"orca": "Orca",
	"ordi": "",
	"orn": "Orion Protocol",
	"osak": "",
	"osmo": "Osmosis",
	"ox_old": "",
	"oxt": "Orchid Network",
	"paal": "",
	"pab": "Panamanian Balboa",
	"pandora": "",
	"pax": "Paxos Standard Token",
	"paxg": "PAX Gold",
	"pci": "Paycoin",
	"pen": "Peruvian Sol",
	"pendle": "Pendle",
	"people": "ConstitutionDAO",
	"pepe": "",
	"pepecoin": "",
	"perp": "Perpetual Protocol",
	"pgk": "Papua New Guinean Kina",
	"php": "Philippine Peso",
	"pixel": "PixelVerse",
	"pkr": "Pakistani Rupee",
	"pla": "PlayDapp",
	"pln": "Polish Zloty",
	"plu": "Pluton",
	"png": "Pangolin",
	"pokt": "Pocket Network",
	"pols": "Polkastarter",
	"poly": "Polymath",
	"polyx": "",
	"pond": "Marlin",
	"ponke": "",
	"popcat": "",
	"pork": "",
	"portal": "",
	"powr": "Powerledger",
	"prime": "Echelon Prime",
	"pro": "Propy",
	"prom": "Prometeus",
	"prq": "PARSIQ",
	"pte": "Portuguese Escudo",
	"pundix": "Pundi X (New)",
	"pups": "",
	"pyg": "Paraguayan Guarani",
	"pyr": "Vulcan Forged PYR",
	"pyth": "",
	"pyusd": "",
	"qar": "Qatari Riyal",
	"qi": "BENQI",
	"qnt": "Quant",
	"qtum": "QTUM",
	"quick": "QuickSwap",
	"rad": "Radicle",
	"rai": "Rai Reflex Index",
	"rare": "SuperRare",
	"rari": "Rarible",
	"ray": "Raydium",
	"rbn": "Ribbon FInance",
	"rei": "",
	"ren": "renBTC",
	"render": "",
	"rep": "Augur",
	"repv2": "REPv2",
	"req": "Request",
	"reth": "Rocket Pool ETH",
	"rgt": "Rari Governance Token",
	"rif": "RIF Token",
	"rlb": "",
	"rlc": "iExec RLC",
	"rly": "Rally",
	"rndr": "Render Token",
	"rol": "Romanian Leu",
	"ron": "Romanian Leu",
	"ronin": "",
	"rose": "Oasis Network",
	"rpl": "Rocket Pool",
	"rsd": "Serbian Dinar",
	"rseth": "",
	"rsr": "Reserve Rights",
	"rss3": "RSS3",
	"rub": "Russian Ruble",
	"rune": "THORChain (ERC20)",
	"rvn": "Ravencoin",
	"rwf": "Rwandan Franc",
	"safe": "SafeCoin",
	"saga": "SagaCoin",
	"sand": "The Sandbox",
	"sar": "Saudi Arabian Riyal",
	"sats": "Satoshi",
	"savax": "",
	"sbd": "Solomon Islander Dollar",
	"sc": "Siacoin",
	"scr": "Seychellois Rupee",
	"sdd": "Sudanese Dinar",
	"sdg": "Sudanese Pound",
	"seam": "",
	"sei": "",
	"sek": "Swedish Krona",
	"sfp": "SafePal",
	"sfrxeth": "",
	"sfund": "Seedify.fund",
	"sgb": "SubGame",
	"sgd": "Singapore Dollar",
	"shdw": "GenesysGo Shadow",
	"shib": "Shiba Inu",
	"shp": "Saint Helenian Pound",
	"shping": "Shping Coin",
	"sit": "Slovenian Tolar",
	"skk": "Slovak Koruna",
	"skl": "SKALE Network",
	"sle": "Sierra Leonean Leone",
	"slerf": "",
	"sll": "Sierra Leonean Leone",
	"slp": "Smooth Love Potion",
	"snt": "Status Network",
	"snx": "Synthetix Network",
	"sol": "Solana",
	"sos": "Somali Shilling",
	"spa": "Sperax",
	"spell": "Spell Token",
	"spl": "Seborgan Luigino",
	"srd": "Surinamese Dollar",
	"srg": "Surinamese Guilder",
	"ssp": "South Sudanese Pound",
	"ssv": "SSVCoin",
	"std": "Sao Tomean Dobra",
	"steth": "Lido stETH",
	"stg": "Stargate Finance",
	"stn": "Sao Tomean Dobra",
	"storj": "Storj",
	"strax": "Stratis",
	"strd": "",
	"strk": "Strike",
	"stsol": "Lido for Solana",
	"stx": "Stacks",
	"sui": "Sui",
	"suku": "SUKU",
	"super": "SuperFarm",
	"sushi": "SushiSwap",
	"svc": "Salvadoran Colon",
	"sweth": "",
	"swftc": "SwftCoin",
	"sxp": "Swipe",
	"sylo": "Sylo",
	"syn": "Synapse",
	"sync": "SyncCoin",
	"syp": "Syrian Pound",
	"szl": "Swazi Lilangeni",
	"t": "Threshold",
	"tao": "",
	"tel": "Telcoin",
	"tet": "",
	"tfuel": "Theta Fuel",
	"thb": "Thai Baht",
	"theta": "Theta",
	"tia": "Tianhe",
	"time": "Chrono.tech",
	"tjs": "Tajikistani Somoni",
	"tkx": "Token X",
	"tmm": "Turkmenistani Manat",
	"tmt": "Turkmenistani Manat",
	"tnd": "Tunisian Dinar",
	"tnsr": "",
	"ton": "Tokamak Network",
	"tone": "TE-FOOD",
	"top": "Tongan Pa'anga",
	"topia": "",
	"tor": "TorCoin",
	"toshi": "",
	"trac": "OriginTrail",
	"trb": "Tellor",
	"tribe": "Tribe",
	"trl": "Turkish Lira",
	"tru": "TrueFi",
	"trump": "TrumpCoin",
	"trx": "TRON",
	"try": "Turkish Lira",
	"ttd": "Trinidadian Dollar",
	"turbo": "",
	"tusd": "True USD",
	"tvd": "Tuvaluan Dollar",
	"tvk": "Terra Virtua Kolect",
	"twd": "Taiwan New Dollar",
	"twt": "Trust Wallet Token",
	"tzs": "Tanzanian Shilling",
	"uah": "Ukrainian Hryvnia",
	"ugx": "Ugandan Shilling",
	"ultima": "",
	"uma": "Universal Market Access",
	"unfi": "Unifi Protocol DAO",
	"uni": "Uniswap",
	"uos": "Ultra",
	"upi": "Pawtocol",
	"uqc": "Uquid Coin",
	"usd": "US Dollar",
	"usdb": "",
	"usdc": "USDC",
	"usdd": "",
	"usde": "UnitaryStatus Dollar",
	"usdp": "USDP Stablecoin",
	"usdt": "Tether",
	"ust": "TerraUSD",
	"ustc": "",
	"uyu": "Uruguayan Peso",
	"uzs": "Uzbekistani Som",
	"val": "Vatican City Lira",
	"vanry": "",
	"vara": "",
	"veb": "Venezuelan Bolívar",
	"ved": "",
	"vef": "Venezuelan Bolívar",
	"velo": "Velo",
	"venom": "",
	"ves": "Venezuelan Bolívar",
	"vet": "Vechain",
	"vgx": "Voyager Token",
	"vnd": "Vietnamese Dong",
	"vnst": "",
	"voxel": "Voxies",
	"vr": "Victoria VR",
	"vtho": "VeChainThor",
	"vuv": "Ni-Vanuatu Vatu",
	"w": "",
	"wampl": "Wrapped Ampleforth",
	"waves": "Waves",
	"waxl": "Axelar",
	"waxp": "WAX",
	"wbeth": "",
	"wbt": "",
	"wbtc": "Wrapped Bitcoin",
	"wcfg": "Wrapped Centrifuge",
	"weeth": "",
	"wemix": "WEMIX",
	"wif": "",
	"wild": "Wild Crypto",
	"wld": "",
	"wluna": "Wrapped LUNA",
	"woo": "WOO Network",
	"wst": "Samoan Tala",
	"wzrd": "",
	"xaf": "Central African CFA Franc BEAC",
	"xag": "Silver Ounce",
	"xai": "SapienceCoin",
	"xau": "Gold Ounce",
	"xaut": "Tether Gold",
	"xbt": "",
	"xcd": "East Caribbean Dollar",
	"xch": "Chia",
	"xcn": "Chain",
	"xdc": "XDC Network",
	"xdr": "IMF Special Drawing Rights",
	"xec": "Eternal Coin",
	"xem": "NEM",
	"xlm": "Stellar Lumen",
	"xmon": "XMON",
	"xmr": "Monero",
	"xof": "CFA Franc",
	"xpd": "Palladium Ounce",
	"xpf": "CFP Franc",
	"xpt": "Platinum Ounce",
	"xrd": "Radix",
	"xrp": "Ripple",
	"xt": "ExtremeCoin",
	"xtz": "Tezos",
	"xvs": "Venus",
	"xyo": "XYO Network",
	"yer": "Yemeni Rial",
	"yfi": "Yearn Finance",
	"yfii": "DFI.Money",
	"ygg": "Yield Guild Games",
	"zar": "South African Rand",
	"zbc": "Zilbercoin",
	"zec": "ZCash",
	"zen": "Horizen",
	"zeta": "",
	"zil": "Zilliqa",
	"zk": "",
	"zmk": "Zambian Kwacha",
	"zmw": "Zambian Kwacha",
	"zro": "",
	"zrx": "ZRX 0x",
	"zwd": "Zimbabwean Dollar",
	"zwl": "Zimbabwean Dollar",
	"zypto": ""
}

export default data